/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bai2;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 7550
 */
public class qlsv extends javax.swing.JFrame {

    /**
     * Creates new form qlsv
     */
    public qlsv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        masvText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hotenText = new javax.swing.JTextField();
        j1 = new javax.swing.JLabel();
        ngaysinhText = new javax.swing.JTextField();
        j2 = new javax.swing.JLabel();
        gioitinhText = new javax.swing.JTextField();
        j3 = new javax.swing.JLabel();
        diemtbText = new javax.swing.JTextField();
        j4 = new javax.swing.JLabel();
        hocphiText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        j5 = new javax.swing.JLabel();
        donviText = new javax.swing.JTextField();
        j7 = new javax.swing.JLabel();
        luongText = new javax.swing.JTextField();
        addattt = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        show = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        addmatma = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Mã SV");

        masvText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masvTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Họ Tên");

        j1.setText("Ngày sinh");

        j2.setText("Giới Tính");

        j3.setText("Điểm TB");

        j4.setText("Học phí");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(table1);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(table2);

        j5.setText("Đơn Vị");

        j7.setText("Lương");

        addattt.setText("ADDATTT");
        addattt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addatttActionPerformed(evt);
            }
        });

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        addmatma.setText("ADDMATMA");
        addmatma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmatmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(j4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(j3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(j2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                            .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hotenText, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(ngaysinhText)
                                .addComponent(gioitinhText)
                                .addComponent(diemtbText)
                                .addComponent(hocphiText)
                                .addComponent(donviText)
                                .addComponent(luongText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(masvText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(addattt)
                        .addGap(29, 29, 29)
                        .addComponent(addmatma)
                        .addGap(39, 39, 39)
                        .addComponent(SAVE)
                        .addGap(52, 52, 52)
                        .addComponent(show)
                        .addGap(70, 70, 70)
                        .addComponent(clear)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(masvText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(hotenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j1)
                            .addComponent(ngaysinhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j2)
                            .addComponent(gioitinhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j3)
                            .addComponent(diemtbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j4)
                            .addComponent(hocphiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j5)
                            .addComponent(donviText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j7)
                            .addComponent(luongText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addmatma)
                                .addComponent(SAVE)
                                .addComponent(show)
                                .addComponent(clear))
                            .addComponent(addattt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masvTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masvTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masvTextActionPerformed

    private void addatttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addatttActionPerformed
        // TODO add your handling code here:
        String masv = masvText.getText();
        String hoten = hotenText.getText();
        String ngaysinh = ngaysinhText.getText();
        String gioitinh = gioitinhText.getText();
        String diemtb = diemtbText.getText();
        String hocphi = hocphiText.getText();
        String donvi = donviText.getText();
        String luong = luongText.getText();
        if(hocphi.equals("")){
                    DefaultTableModel model2 = (DefaultTableModel) table2.getModel() ;
                    model2.addRow(new Object[]{masv,hoten,ngaysinh,gioitinh,diemtb,donvi,luong});
                    SinhVienMatMa student=new SinhVienMatMa();
                    student.setMasv(masv);
                    student.setHoten(hoten);
                    student.setNgaysinh(ngaysinh);
                    student.setGioitinh(gioitinh);
                    student.setDiemtrungbinh(diemtb);
                    student.setDonvi(donvi);
                    student.setLuong(luong);
        }
        if(donvi.equals("") && luong.equals("")){
                    DefaultTableModel model1 = (DefaultTableModel) table1.getModel() ;
                    model1.addRow(new Object[]{masv,hoten,ngaysinh,gioitinh,diemtb,hocphi});
                    SinhVienATTT student=new SinhVienATTT();
                    student.setMasv(masv);
                    student.setHoten(hoten);
                    student.setNgaysinh(ngaysinh);
                    student.setGioitinh(gioitinh);
                    student.setDiemtrungbinh(diemtb);
                    student.setHocphi(hocphi);
        }       
        
    }//GEN-LAST:event_addatttActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) table1.getModel() ;
        Vector<Vector> tableData1 = model1.getDataVector();
        FileOutputStream fos;
        ObjectOutputStream oos;
        try {
            fos = new FileOutputStream("qlsv1.dat");
            oos = new ObjectOutputStream(fos);
            oos.writeObject(tableData1);
            oos.close();
            fos.close();
        } catch (Exception e) {
        }
        DefaultTableModel model2 = (DefaultTableModel) table2.getModel() ;
        Vector<Vector> tableData2 = model2.getDataVector();
        try {
            fos = new FileOutputStream("qlsv2.dat");
            oos = new ObjectOutputStream(fos);
            oos.writeObject(tableData2);
            oos.close();
            fos.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SAVEActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        FileInputStream fis;
        ObjectInputStream  ois;
        try {
            fis = new FileInputStream("qlsv1.dat");
            ois = new ObjectInputStream(fis);
            //đọc file
            Vector<Vector> tableData1 = ( Vector<Vector>) ois.readObject();
            
            fis.close();
            ois.close();
            DefaultTableModel model1 = (DefaultTableModel) table1.getModel() ;
            for (int i=0; i<tableData1.size();i++){
                Vector row = tableData1.get(i);
                //hiển thị giá trị lên table
                model1.addRow(new Object[]{row.get(0),row.get(1),row.get(2),row.get(3),row.get(4),row.get(5)});
            }
        } catch (Exception e) {
        }
        try {
            fis = new FileInputStream("qlsv2.dat");
            ois = new ObjectInputStream(fis);
            //đọc file
            Vector<Vector> tableData2 = ( Vector<Vector>) ois.readObject();
            
            fis.close();
            ois.close();
            DefaultTableModel model2 = (DefaultTableModel) table2.getModel() ;
            for (int i=0; i<tableData2.size();i++){
                Vector row = tableData2.get(i);
                //hiển thị giá trị lên table
                model2.addRow(new Object[]{row.get(0),row.get(1),row.get(2),row.get(3),row.get(4),row.get(5),row.get(6)});
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_showActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) table1.getModel() ;
        if (model1.getRowCount() > 0) {
                    for (int i = model1.getRowCount() - 1; i > -1; i--) {
                        model1.removeRow(i);
                    }
                }
        DefaultTableModel model2 = (DefaultTableModel) table2.getModel() ;
        if (model2.getRowCount() > 0) {
                    for (int i = model2.getRowCount() - 1; i > -1; i--) {
                        model2.removeRow(i);
                    }
                }
    }//GEN-LAST:event_clearActionPerformed

    private void addmatmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmatmaActionPerformed
        // TODO add your handling code here:
        String masv = masvText.getText();
        String hoten = hotenText.getText();
        String ngaysinh = ngaysinhText.getText();
        String gioitinh = gioitinhText.getText();
        String diemtb = diemtbText.getText();
        String hocphi = hocphiText.getText();
        String donvi = donviText.getText();
        String luong = luongText.getText();
        DefaultTableModel model2 = (DefaultTableModel) table2.getModel() ;
        model2.addRow(new Object[]{masv,hoten,ngaysinh,gioitinh,diemtb,donvi,luong});
        SinhVienMatMa attt = new SinhVienMatMa();
        attt.setHoten(hoten);
        attt.setMasv(masv);
        attt.setNgaysinh(ngaysinh);
        attt.setGioitinh(gioitinh);
        attt.setDiemtrungbinh(diemtb);
        attt.setDonvi(donvi);
        attt.setLuong(luong);
    }//GEN-LAST:event_addmatmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qlsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qlsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qlsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qlsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qlsv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAVE;
    private javax.swing.JButton addattt;
    private javax.swing.JButton addmatma;
    private javax.swing.JButton clear;
    private javax.swing.JTextField diemtbText;
    private javax.swing.JTextField donviText;
    private javax.swing.JTextField gioitinhText;
    private javax.swing.JTextField hocphiText;
    private javax.swing.JTextField hotenText;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField luongText;
    private javax.swing.JTextField masvText;
    private javax.swing.JTextField ngaysinhText;
    private javax.swing.JButton show;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
